### ISSUE TITLE
ServiceHostConfigTool.exe error

### ISSUE THREAD

**Issue by JaySardhara** [versionone/VersionOne.Integration.JIRA#16]
Hi,

I am trying to build ServiceHostConfigTool.exe from Visual Studio and using latest build/source code.

When I run exe, I am getting below exception.
(Although, ServiceHostConfigTool.exe downloaded from [official link](http://appcatalog.versionone.com/app/index.html#/Details/VersionOne.Integration.JIRA) ) link works fine.

`************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: dataSource
   at System.Windows.Forms.ControlBindingsCollection.Add(String propertyName, Object dataSource, String dataMember, Boolean formattingEnabled, DataSourceUpdateMode updateMode, Object nullValue, String formatString, IFormatProvider formatInfo)
   at System.Windows.Forms.ControlBindingsCollection.Add(String propertyName, Object dataSource, String dataMember, Boolean formattingEnabled, DataSourceUpdateMode updateMode)
   at VersionOne.ServiceHost.ConfigurationTool.UI.Controls.BaseDataBindingControl.AddControlBinding(Control control, Object dataSource, String dataMember) in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\UI\Controls\BaseDataBindingControl.cs:line 42
   at VersionOne.ServiceHost.ConfigurationTool.UI.Controls.V1SettingsPageControl.DataBind() in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\UI\Controls\V1SettingsPageControl.cs:line 34
   at VersionOne.ServiceHost.ConfigurationTool.UI.Controllers.BasePageController`2.PrepareView() in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\UI\Controllers\BaseController.cs:line 53
   at VersionOne.ServiceHost.ConfigurationTool.UI.Controllers.GeneralController.PrepareView() in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\UI\Controllers\GeneralController.cs:line 11
   at VersionOne.ServiceHost.ConfigurationTool.UI.UIFactory.GetNextPage(String pageKey, ServiceHostConfiguration model, IFormController formController) in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\UI\UIFactory.cs:line 100
   at VersionOne.ServiceHost.ConfigurationTool.ConfigurationFormController.ShowPage(String pageKey) in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\ConfigurationFormController.cs:line 57
   at VersionOne.ServiceHost.ConfigurationTool.ConfigurationForm.tvServices_AfterSelect(Object sender, TreeViewEventArgs e) in C:\Users\s\Desktop\VersionOne.Integration.JIRA-master\VersionOne.ServiceHost.ConfigurationTool\ConfigurationForm.cs:line 118
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

Thanks.

**Comment by JaySardhara** [comment]
Solved by including all dependencies while building solution, as by default partial dependencies are selected.
